/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommonSubscriptionAvatarEditor: typeof import('./components/CommonSubscriptionAvatarEditor.vue')['default']
    CommonSubscriptionModal: typeof import('./components/CommonSubscriptionModal.vue')['default']
    CurrencySelect: typeof import('./components/CurrencySelect.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ImportExportDrawer: typeof import('./components/ImportExportDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchedulerStatusCard: typeof import('./components/SchedulerStatusCard.vue')['default']
    StatsOverview: typeof import('./components/StatsOverview.vue')['default']
    SubscriptionBrandIcon: typeof import('./components/SubscriptionBrandIcon.vue')['default']
    SubscriptionDetailDrawer: typeof import('./components/SubscriptionDetailDrawer.vue')['default']
    SubscriptionModal: typeof import('./components/SubscriptionModal.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
